apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kubernetes-barklund
  name: kubernetes-barklund
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: kubernetes-barklund
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kubernetes-barklund
    spec:
      containers:
      - image: gcr.io/kubernetes-workshop-235208/github.com/barklund/kubernetes-workshop-21:{{ .sha }}
        imagePullPolicy: IfNotPresent
        name: kubernetes-barklund
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
