apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kubernetes-barklund
  name: kubernetes-barklund
  namespace: default
spec:
  selector:
    matchLabels:
      run: kubernetes-barklund
  template:
    metadata:
      labels:
        run: kubernetes-barklund
    spec:
      containers:
        - image: gcr.io/kubernetes-workshop-235208/github.com/barklund/kubernetes-workshop-21:{{ .sha }}
          name: nodejs-cloudbuild-kubernetes
          ports:
            - containerPort: 9000
